Test wasm32-wasi

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,114 +22,117 @@ jobs:
         llvm_version: ["23.1.1"]
         llvm_build_type: ["Release", "Debug"]
         target:
-          - id: "linux-amd64"
-            os: "ubuntu-22.04"
+          # - id: "linux-amd64"
+          #   os: "ubuntu-22.04"
 
-          - id: "linux-aarch64"
-            os: "ubuntu-24.04-arm"
+          # - id: "linux-aarch64"
+          #   os: "ubuntu-24.04-arm"
 
-          - id: "linux-riscv64"
-            os: "ubuntu-24.04"
+          # - id: "linux-riscv64"
+          #   os: "ubuntu-24.04"
 
-          - id: "linux-amd64-musl"
-            os: "ubuntu-latest"
-            container: "alpine:3.23"
+          # - id: "linux-amd64-musl"
+          #   os: "ubuntu-latest"
+          #   container: "alpine:3.23"
 
-          - id: "darwin-amd64"
-            os: "macos-15-intel"
+          # - id: "darwin-amd64"
+          #   os: "macos-15-intel"
 
-          - id: "darwin-aarch64"
-            os: "macos-latest"
+          # - id: "darwin-aarch64"
+          #   os: "macos-latest"
 
-          - id: "windows-amd64"
-            os: "windows-2022"
-            tar_extra_args: "--dereference" # On Windows, symlinks require existing targets, so archives may fail. Dereferencing stores copies instead, slightly increasing size but ensuring reliable unpacking.
+          # - id: "windows-amd64"
+          #   os: "windows-2022"
+          #   tar_extra_args: "--dereference" # On Windows, symlinks require existing targets, so archives may fail. Dereferencing stores copies instead, slightly increasing size but ensuring reliable unpacking.
 
-          - id: "windows-aarch64"
-            os: "windows-11-arm"
-            tar_extra_args: "--dereference"
+          # - id: "windows-aarch64"
+          #   os: "windows-11-arm"
+          #   tar_extra_args: "--dereference"
 
           - id: "wasm32-emscripten"
             os: "ubuntu-24.04"
 
+          - id: "wasm32-wasi"
+            os: "ubuntu-24.04"
+
     runs-on: ${{ matrix.target.os }}
-    container: ${{ matrix.target.container }}
+    # container: ${{ matrix.target.container }}
 
     steps:
       - name: Check out the code
         uses: actions/checkout@v6
 
-      - name: Install dependencies (musl)
-        if: matrix.target.id == 'linux-amd64-musl'
-        run: |
-          apk add --no-cache \
-            build-base bash git cmake ninja python3 linux-headers \
-            zlib-dev zlib-static zstd-dev zstd-static curl-dev libffi-dev xz
+      # - name: Install dependencies (musl)
+      #   if: matrix.target.id == 'linux-amd64-musl'
+      #   run: |
+      #     apk add --no-cache \
+      #       build-base bash git cmake ninja python3 linux-headers \
+      #       zlib-dev zlib-static zstd-dev zstd-static curl-dev libffi-dev xz
 
-      - name: Free Disk Space (Linux glibc only)
-        if: startsWith(matrix.target.id, 'linux-') && matrix.target.id != 'linux-amd64-musl'
-        run: |
-          sudo docker system prune --all --force --volumes || true
-          sudo rm -rf \
-            /usr/share/dotnet \
-            /usr/local/lib/android \
-            /opt/android \
-            /opt/ghc \
-            /usr/local/.ghcup \
-            /home/runner/.ghcup \
-            /home/runner/.cabal \
-            /usr/share/swift \
-            /usr/share/miniconda \
-            /usr/local/julia \
-            /usr/share/az* \
-            /usr/local/aws-cli \
-            /usr/local/aws-sam-cli \
-            /usr/local/share/powershell \
-            /usr/local/share/chromium \
-            /usr/local/lib/node_modules \
-            /usr/share/gradle \
-            "${AGENT_TOOLSDIRECTORY:-/opt/hostedtoolcache}"
+      # - name: Free Disk Space (Linux glibc only)
+      #   if: startsWith(matrix.target.id, 'linux-') && matrix.target.id != 'linux-amd64-musl'
+      #   run: |
+      #     sudo docker system prune --all --force --volumes || true
+      #     sudo rm -rf \
+      #       /usr/share/dotnet \
+      #       /usr/local/lib/android \
+      #       /opt/android \
+      #       /opt/ghc \
+      #       /usr/local/.ghcup \
+      #       /home/runner/.ghcup \
+      #       /home/runner/.cabal \
+      #       /usr/share/swift \
+      #       /usr/share/miniconda \
+      #       /usr/local/julia \
+      #       /usr/share/az* \
+      #       /usr/local/aws-cli \
+      #       /usr/local/aws-sam-cli \
+      #       /usr/local/share/powershell \
+      #       /usr/local/share/chromium \
+      #       /usr/local/lib/node_modules \
+      #       /usr/share/gradle \
+      #       "${AGENT_TOOLSDIRECTORY:-/opt/hostedtoolcache}"
 
-      - name: Maximize Swap Space (glibc only)
-        if: startsWith(matrix.target.id, 'linux-') && matrix.target.id != 'linux-amd64-musl'
-        uses: pierotofy/set-swap-space@master
-        with:
-          swap-size-gb: 5
+      # - name: Maximize Swap Space (glibc only)
+      #   if: startsWith(matrix.target.id, 'linux-') && matrix.target.id != 'linux-amd64-musl'
+      #   uses: pierotofy/set-swap-space@master
+      #   with:
+      #     swap-size-gb: 5
 
-      - name: Install ninja (Linux glibc & WASM host)
-        if: (startsWith(matrix.target.id, 'linux-') || matrix.target.id == 'wasm32-emscripten') && matrix.target.id != 'linux-amd64-musl'
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y ninja-build zlib1g-dev libzstd-dev
+      # - name: Install ninja (Linux glibc & WASM host)
+      #   if: (startsWith(matrix.target.id, 'linux-') || matrix.target.id == 'wasm32-emscripten') && matrix.target.id != 'linux-amd64-musl'
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y ninja-build zlib1g-dev libzstd-dev
 
-      - name: Install cross-compilation tools (RISCV)
-        if: matrix.target.id == 'linux-riscv64'
-        run: |
-          sudo dpkg --add-architecture riscv64
-          find /etc/apt/ -type f -name "*.list" -o -name "sources.list" | xargs -r grep -l "^deb " | xargs -r sudo sed -i -E "s/^deb\s+([^\[])/deb [arch=$(dpkg --print-architecture)] \1/"
-          find /etc/apt/sources.list.d/ -type f -name "*.sources" | xargs -r sudo sed -i "/^Types: deb/a Architectures: $(dpkg --print-architecture)"
+      # - name: Install cross-compilation tools (RISCV)
+      #   if: matrix.target.id == 'linux-riscv64'
+      #   run: |
+      #     sudo dpkg --add-architecture riscv64
+      #     find /etc/apt/ -type f -name "*.list" -o -name "sources.list" | xargs -r grep -l "^deb " | xargs -r sudo sed -i -E "s/^deb\s+([^\[])/deb [arch=$(dpkg --print-architecture)] \1/"
+      #     find /etc/apt/sources.list.d/ -type f -name "*.sources" | xargs -r sudo sed -i "/^Types: deb/a Architectures: $(dpkg --print-architecture)"
 
-          # Add the RISC-V ports mirror
-          echo "deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports noble main universe restricted multiverse" | sudo tee /etc/apt/sources.list.d/riscv64.list
-          echo "deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports noble-updates main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list.d/riscv64.list
-          echo "deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports noble-security main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list.d/riscv64.list
+      #     # Add the RISC-V ports mirror
+      #     echo "deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports noble main universe restricted multiverse" | sudo tee /etc/apt/sources.list.d/riscv64.list
+      #     echo "deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports noble-updates main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list.d/riscv64.list
+      #     echo "deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports noble-security main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list.d/riscv64.list
 
-          sudo apt-get update
-          sudo apt-get install -y \
-            gcc-13-riscv64-linux-gnu g++-13-riscv64-linux-gnu \
-            gcc-13-multilib binutils-riscv64-linux-gnu \
-            libgcc-13-dev-riscv64-cross libstdc++6-riscv64-cross \
-            zlib1g-dev:riscv64 libzstd-dev:riscv64
+      #     sudo apt-get update
+      #     sudo apt-get install -y \
+      #       gcc-13-riscv64-linux-gnu g++-13-riscv64-linux-gnu \
+      #       gcc-13-multilib binutils-riscv64-linux-gnu \
+      #       libgcc-13-dev-riscv64-cross libstdc++6-riscv64-cross \
+      #       zlib1g-dev:riscv64 libzstd-dev:riscv64
 
-      - name: Install ninja (macOS)
-        if: startsWith(matrix.target.id, 'darwin-')
-        run: command -v ninja >/dev/null || brew install ninja
+      # - name: Install ninja (macOS)
+      #   if: startsWith(matrix.target.id, 'darwin-')
+      #   run: command -v ninja >/dev/null || brew install ninja
 
-      - name: Setup MSVC (Windows)
-        uses: TheMrMilchmann/setup-msvc-dev@v4
-        with:
-          arch: ${{ matrix.target.id == 'windows-aarch64' && 'arm64' || 'x64' }}
-        if: startsWith(matrix.target.id, 'windows-')
+      # - name: Setup MSVC (Windows)
+      #   uses: TheMrMilchmann/setup-msvc-dev@v4
+      #   with:
+      #     arch: ${{ matrix.target.id == 'windows-aarch64' && 'arm64' || 'x64' }}
+      #   if: startsWith(matrix.target.id, 'windows-')
 
       - name: Setup Emscripten (WebAssembly)
         if: matrix.target.id == 'wasm32-emscripten'
@@ -138,21 +141,26 @@ jobs:
           version: "latest"
           actions-cache-folder: "emsdk-cache"
 
+      - name: Setup WASI (WebAssembly)
+        if: matrix.target.id == 'wasm32-wasi'
+        uses: bytecodealliance/setup-wasi-sdk-action@v1
+        
       - name: Build
         shell: bash
         run: |
-          if [ "${{ matrix.target.id }}" = "wasm32-emscripten" ]; then
+          # if [[ "${{ matrix.target.id }}" == "wasm32-emscripten" || "${{ matrix.target.id }}" == "wasm32-wasi" ]]; then
             ./build_wasm.sh \
-              ${{ matrix.llvm_version }} \
-              ${{ env.LLVM_REPO_URL }} \
-              ${{ matrix.llvm_build_type }}
-          else
-            ./build.sh \
               ${{ matrix.llvm_version }} \
               ${{ env.LLVM_REPO_URL }} \
               ${{ matrix.target.id }} \
               ${{ matrix.llvm_build_type }}
-          fi
+          # else
+          #   ./build.sh \
+          #     ${{ matrix.llvm_version }} \
+          #     ${{ env.LLVM_REPO_URL }} \
+          #     ${{ matrix.target.id }} \
+          #     ${{ matrix.llvm_build_type }}
+          # fi
 
       - name: Package
         shell: bash
